name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-size:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build library
      run: npm run build
    
    - name: Check bundle size
      run: |
        echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|" >> $GITHUB_STEP_SUMMARY
        for file in dist/*.js; do
          if [ -f "$file" ]; then
            size=$(ls -lh "$file" | awk '{print $5}')
            echo "| $(basename "$file") | $size |" >> $GITHUB_STEP_SUMMARY
          fi
        done

  check-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Check for security vulnerabilities
      run: npm audit --production || true
    
    - name: Check for outdated dependencies
      run: |
        echo "## Outdated Dependencies" >> $GITHUB_STEP_SUMMARY
        npm outdated --long >> $GITHUB_STEP_SUMMARY || true